# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-west-2
  AWS_IAM_ROLE: arn:aws:iam::196022043749:role/github-actions

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout
      
# jobs:
#   AssumeRoleAndCallIdentity:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v3
#       - name: configure aws credentials
#         uses: aws-actions/configure-aws-credentials@v1.7.0
#         with:
#           role-to-assume: arn:aws:iam::196022043749:role/github-actions
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#       # Hello from AWS: WhoAmI
#       - name: Sts GetCallerIdentity
#         run: |
#           aws sts get-caller-identity

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Release new version
        id: release
        run: |
          bash ./scripts/git_update.sh -v patch

      - name: Add app version (Optional)
        run: echo ${{ steps.release.outputs.new-tag }} > version.txt

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REPOSITORY: ${{ github.repository }}
          ECR_REPOSITORY: justcatchingrye/app-lesson-268
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

